root = "." # The root directory of the project
tmp_dir = "tmp" # The temporary directory where air will store its temporary files

[build] # The build configuration
  bin = "main"
  cmd = "go build -o {{.Output}} {{.Input}}"
  exclude = ["tmp/*", "client/*"]
  include = ["**/*.go"]
  ignore = ["tmp/*"]